name: Module Builder

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Zip Files
      working-directory: ./
      run: zip -r ./checks-and-saves-macros.zip ./*

    - name: Get Version
      shell: bash
      id: get-version
      run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create-release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true  # Allow updates to existing releases
        name: Release ${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './checks-and-saves-macros.zip, ./module.json'
        tag: ${{ steps.get-version.outputs.version }}